### ISSUE TITLE
md-spinner with IE11

### ISSUE THREAD

**Issue by Aymkdn** [vuematerial/vue-material#1016]
Hi,

The ` md-spinner` with `md-indeterminate` doesn't look very good with IE11 because IE11 doesn't support animation on stroke-dasharray. It's possible to change the behavior for IE11 by detecting the browser (using [browserhacks.com](http://browserhacks.com/)) and add a special class for it.

Then you can define the new animation for the spinner for IE11 only:
```css
.ie11 .md-spinner.md-indeterminate .md-spinner-draw { animation: spinner-rotate 3s linear infinite }
.ie11 .md-spinner.md-indeterminate .md-spinner-path { stroke-dasharray: 20,20 }
```

The result can be found on https://codepen.io/Aymkdn/pen/YxMpVY

It's not perfect, but the animation looks better.

I have no inspiration, nor time right now to improve this animation, but at least it will give a direction for people who try to have it to work with IE11.

Thanks
