### ISSUE TITLE
Table column does not expand to width of cell's input-container

### ISSUE THREAD

**Issue by hanxue** [vuematerial/vue-material#1121]
### Steps to reproduce

1. Create a table column with a short table header text
2. Table cell is a `<input-container>` with long `<label>` text

The table cell's label text will be wrapped

![image](https://user-images.githubusercontent.com/760008/32643423-56096b6a-c616-11e7-90a1-e8242df574ac.png)

### Environment

vue: 2.4.2
vue-material: 0.7.4
MacOS: 10.10.5
Chrome: 64.0.3262.0

### What is expected?

Table column will extend to the length of the `<input-container>`

### Reproduction Link

https://codepen.io/hanxue/pen/gXmYKo

**Comment by VdustR** [comment]
We could try `ellipsis`:

```css
.md-input-container label {
    white-space: nowrap;
    text-overflow: ellipsis;
    width: 100%;
    overflow: hidden;
}
```
