### ISSUE TITLE
importing scoped scss doesn't work

### ISSUE THREAD

**Issue by dtruel** [vuematerial/vue-material#1378]
I'm trying to contain the css styles in the vue 1.0 beta like so.  The idea would be that the css styles would only apply to things that are children of a .vue-component element.

This is my code:
```scss
.vue-component{

    @import "{}/node_modules/vue-material/dist/theme/engine.scss"; // Import the theme engine

    @include md-register-theme("default", (
        primary: md-get-palette-color(green, A200), // The primary color of your application
        accent: md-get-palette-color(pink, 500) // The accent or secondary color
    ));
    .name{
        color:"red";
    }
    @import "{}/node_modules/vue-material/dist/theme/all.scss"; // Apply the theme
}
```
All it produces is a file with comments and this:
```
  .vue-component :root {
    --md-theme-default-primary: #69f0ae;
    --md-theme-default-accent: #e91e63;
    --md-theme-default-theme: "light"; }
```

If I remove the `.vue-component` it spits out the whole file as it should.  I really need to have this css scoped, but the loading functions are so complicated I can't figure out what's going on.
