### ISSUE TITLE
Localization and chinese font for vue-material

### ISSUE THREAD

**Issue by hanxue** [vuematerial/vue-material#1466]
### Problem

I am unable to change the default font for vue-material apps. I have added the following CSS

```css
@font-face {
  font-family: 'Microsoft Yahei', '微软雅黑', '宋体';
  font-style: normal;
  font-weight: normal;
  src: local('Microsoft Yahei'), local('微软雅黑');
}
@font-face {
  font-family: 'STXihei', '华文细黑', '宋体';
  font-style: normal;
  font-weight: normal;
  src: local('STXihei'), local('华文细黑');
}
```

But when inspecting the Chinese text, the font is still unchanged. 

![image](https://user-images.githubusercontent.com/760008/35684025-9c4a2cba-07a0-11e8-898c-1b4403401bbb.png)

How do I change the default font for a vue-material app?

### Reproduction Link

https://codepen.io/hanxue/pen/MQamzv
