### ISSUE TITLE
[Style] not applying focus on autofocus elements

### ISSUE THREAD

**Issue by jimmywarting** [vuematerial/vue-material#1554]
I used `autofocus` attribute on an element but the button didn't look like it had focus but it did.
I notice the style only gets applied if the `md-focused` class is added but it wasn't there

Are there any reason for not using `:focus`?

**Comment by Samuell1** [comment]
Because focus needs to be sended to `md-field` component to show line under input.

**Comment by jimmywarting** [comment]
Ok, then i understand the reason behind the behaviour.
but for my case it's just a button and it don't have to be wrapped with any outer element.

so just extending the [md-button] with a `:focus` would be safe to add

```css
  .md-button:not([disabled]):focus:before {
      background-color: currentColor;
      opacity: .12;
  }
```

Regarding the `md-fields`... the solution is to use [:focus-within](https://developer.mozilla.org/en-US/docs/Web/CSS/:focus-within) but Edge lacks supports
