### ISSUE TITLE
beta: use dist/theme/functions.scss function to style my custom element

### ISSUE THREAD

**Issue by jbjuin** [vuematerial/vue-material#1587]
### Steps to reproduce

- Start a webpack project with vue-cli and install scss loaders.
- Add VueMaterial **beta**
- Create a vue component (.vue file) with style "scss"
- Try to get the primary color from your theme to style a custom component using theme "functions": `md-theme` (in the `dist/theme/functions.scss` file).

```scss

<style lang="scss">
.main-menu {
    color: white;
    position: fixed;
    top: 0;
    left: 0;
    width: 100%;
    background-color: md-theme(primary);
}

</style>
```

### Which browser?

- Vue: 3.0.1
- VueMaterial: 1.0.0-beta-7
- Recent browsers: firefox & chrome

### What is expected?

My custom component should have the primary color as `background-color`.

### What is actually happening?

My custom component background color is not set to my theme primary color.

Note that the material element: `md-button` colors do change when I update
my theme palette. So everything seems to work except that I cannot call that function.

### Reproduction Link

I could not make vue-material@beta to work in codepen :(. Sorry.
Here is my try to make it work: https://codepen.io/anon/pen/mxboRY
