### ISSUE TITLE
[MdButton][MdAppToolbar] Primary background color not working 

### ISSUE THREAD

**Issue by davidhoeck** [vuematerial/vue-material#1650]
In my `app.scss` I put the following code to customize the default theme.  
```scss
@import "~vue-material/dist/theme/engine"; // Import the theme engine

@include md-register-theme("default", (
  primary: #d3af72, // The primary color of your application
  accent: #333, // The accent or secondary color
));

@import "~vue-material/dist/theme/all"; // Apply the theme
```

### What is expected?

Primary components should have the primary background.

### What is actually happening?

The components have a transparent background. Because the background color is set to 
```css
 background-color: var(--md-theme-default-primary, #d3af72); 
```

**Comment by davidhoeck** [comment]
@Samuell1 I know that. It already worked. And it is not white .. it is transparent.

**Comment by Samuell1** [comment]
@davidhoeck oh yeah, then md-primary works for you?

**Comment by Nevenall** [comment]
I have the same issue. 
My app.vue contains
```
<style lang="scss" scoped>
@import url("https://fonts.googleapis.com/css?family=Roboto:300,400,500,700,400italic");
@import url("https://fonts.googleapis.com/icon?family=Material+Icons");

@import "~vue-material/dist/theme/engine";

@include md-register-theme("default", (
   primary: #200a33, 
   accent: rgb(245, 214, 11), 
   theme: dark
));

@import "~vue-material/dist/theme/all";
```
The colors didn't work until I added `scoped` to the `<style>` element. However, `scoped` is interfering with my other styling.

**Comment by Samuell1** [comment]
@Nevenall best is to put theme things in separate .scss file

**Comment by wonderful-panda** [comment]
I faced similar problem, and it seems to be a problem depends on node-sass version.

```javascript
var sass = require("node-sass");
var source = `
@import "node_modules/vue-material/dist/theme/engine";
@include md-register-theme("default", (
  primary: #d3af72,
  accent: #333,
));
@import "node_modules/vue-material/dist/theme/all"; 
`;
var css = sass.renderSync({ data: source }).css.toString();
var start = css.indexOf(":root");
var end = css.indexOf("}", start) + 1;;
console.log(css.slice(start, end));
```

Above code outputs this result with node-sass 4.7.2

```css
:root {
  --md-theme-default-primary: #d3af72;
  --md-theme-default-accent: #333;
  --md-theme-default-theme: "light"; }
```

And outputs this with node-sass 4.8.3

```css
:root {
  --md-theme-default-primary: $value
    ;
  --md-theme-default-accent: $value
    ;
  --md-theme-default-theme: $value
    ; }
...
```
