### ISSUE TITLE
Button in toolbar doesn't look disabled even when it is

### ISSUE THREAD

**Issue by DarthGandalf** [vuematerial/vue-material#1950]
### Steps to reproduce

```vue
<md-toolbar class="md-primary">
  <md-button class="md-icon-button" :disabled="true">
    <md-icon>done</md-icon>
  </md-button>
</md-toolbar>
```

### Which browser?

Tested on Firefox 62 and Chromium 69.
Vue 2.5.17, Vue-material 1.0.0-beta-10.2

### What is expected?

The button should be gray

### What is actually happening?

The button is white

### Reproduction Link

https://codesandbox.io/s/q7qqr98ryj

**Comment by Samuell1** [comment]
This is because toolbar should not have disabled buttons, because we change colors of buttons because of toolbar background.

**Comment by Samuell1** [comment]
Maybe we can somehow apply only to non disabled buttons, there is class `.md-toolbar.md-theme-default.md-primary .md-icon` then on that is set `color: #fff;`

**Comment by DarthGandalf** [comment]
For now my workaround for this issue is to add this to my code:
```css
.md-toolbar .md-button[disabled] .md-icon {
    color: var(--md-theme-default-disabled-on-background, rgba(0,0,0,0.26));
}
```
But it feels like a dirty hack.
