### ISSUE TITLE
[md-layout] A small suggestion for improvement

### ISSUE THREAD

**Issue by Elvanos** [vuematerial/vue-material#2114]
After tinkering with the layout of this awesome pack, I realized that the layout system is missing one relatively important feature of Flex display.

**Issue:**

> The layout module doesn't allow for auto-scaling the width of the `md-layout-item` elements based on the width of their own content.

**Solution:**

> I propose adding the following code to the Layout module:

```css
.md-layout-item.md-size-auto{
  flex-grow: 0;
  flex-shrink: 1;
}
```
