### ISSUE TITLE
[Feature request] Add badges

### ISSUE THREAD

**Issue by mtpc** [vuematerial/vue-material#364]
See https://getmdl.io/components/#badges-section or http://www.material-ui.com/#/components/badge

**Comment by marcosmoura** [comment]
This will be done in the near future. Right before the <md-steppers> components.

**Comment by lmj0011** [comment]
:eyes: ?

**Comment by agnivade** [comment]
Hi there ! Great project. I am currently planning to start a new project with Vue and material design. And badge is something that I need. Any estimates around when this is going to be completed ?

**Comment by lmj0011** [comment]
@agnivade 

here's the css you can use to implement it yourself for now.

```css
  .badge:after{
    content:"";
    position: absolute;
    background: rgba(255, 0, 0, 0.85);
    height:1rem;
    top:1rem;
    right:1rem;
    width:1rem;
    text-align: center;
    line-height: 2rem;;
    font-size: 1rem;
    border-radius: 50%;
    color:white;
}
```

then apply it to a material design button, like this:

```html
<md-button :class="md-fab md-primary md-fab-bottom-right badge">
    <md-icon md-iconset="fa fa-list-alt"></md-icon>
</md-button>
```
