### ISSUE TITLE
The checkbox image can shrink when using a lot of text.

### ISSUE THREAD

**Issue by davidhooey** [vuematerial/vue-material#624]
http://codepen.io/davidhooey/pen/evMGyJ/

This seems to fix the shrinking issue.

```css
.md-checkbox .md-checkbox-container {
    min-width: 20px;
}
```

NOTE: switches have the same problem.
